/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ComparePrescriptionDrugPricesRouteImport } from './routes/compare-prescription-drug-prices'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as HowOftenDoesNadacUpdateRouteImport } from './routes/how-often-does-nadac-update'
import { Route as MoversRouteImport } from './routes/movers'
import { Route as NdcLookupRouteImport } from './routes/ndc-lookup'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ReimbursementCalculatorRouteImport } from './routes/reimbursement-calculator'
import { Route as SavedCalculationsRouteImport } from './routes/saved-calculations'
import { Route as SavedDrugsRouteImport } from './routes/saved-drugs'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as WhatIsNadacRouteImport } from './routes/what-is-nadac'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as DrugSlugRouteImport } from './routes/drug/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparePrescriptionDrugPricesRoute =
  ComparePrescriptionDrugPricesRouteImport.update({
    id: '/compare-prescription-drug-prices',
    path: '/compare-prescription-drug-prices',
    getParentRoute: () => rootRouteImport,
  } as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const HowOftenDoesNadacUpdateRoute = HowOftenDoesNadacUpdateRouteImport.update({
  id: '/how-often-does-nadac-update',
  path: '/how-often-does-nadac-update',
  getParentRoute: () => rootRouteImport,
} as any)
const MoversRoute = MoversRouteImport.update({
  id: '/movers',
  path: '/movers',
  getParentRoute: () => rootRouteImport,
} as any)
const NdcLookupRoute = NdcLookupRouteImport.update({
  id: '/ndc-lookup',
  path: '/ndc-lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ReimbursementCalculatorRoute = ReimbursementCalculatorRouteImport.update({
  id: '/reimbursement-calculator',
  path: '/reimbursement-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedCalculationsRoute = SavedCalculationsRouteImport.update({
  id: '/saved-calculations',
  path: '/saved-calculations',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedDrugsRoute = SavedDrugsRouteImport.update({
  id: '/saved-drugs',
  path: '/saved-drugs',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatIsNadacRoute = WhatIsNadacRouteImport.update({
  id: '/what-is-nadac',
  path: '/what-is-nadac',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DrugSlugRoute = DrugSlugRouteImport.update({
  id: '/drug/$slug',
  path: '/drug/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/compare-prescription-drug-prices': typeof ComparePrescriptionDrugPricesRoute
  '/features': typeof FeaturesRoute
  '/how-often-does-nadac-update': typeof HowOftenDoesNadacUpdateRoute
  '/movers': typeof MoversRoute
  '/ndc-lookup': typeof NdcLookupRoute
  '/pricing': typeof PricingRoute
  '/reimbursement-calculator': typeof ReimbursementCalculatorRoute
  '/saved-calculations': typeof SavedCalculationsRoute
  '/saved-drugs': typeof SavedDrugsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/what-is-nadac': typeof WhatIsNadacRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/drug/$slug': typeof DrugSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/compare-prescription-drug-prices': typeof ComparePrescriptionDrugPricesRoute
  '/features': typeof FeaturesRoute
  '/how-often-does-nadac-update': typeof HowOftenDoesNadacUpdateRoute
  '/movers': typeof MoversRoute
  '/ndc-lookup': typeof NdcLookupRoute
  '/pricing': typeof PricingRoute
  '/reimbursement-calculator': typeof ReimbursementCalculatorRoute
  '/saved-calculations': typeof SavedCalculationsRoute
  '/saved-drugs': typeof SavedDrugsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/what-is-nadac': typeof WhatIsNadacRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/drug/$slug': typeof DrugSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/compare-prescription-drug-prices': typeof ComparePrescriptionDrugPricesRoute
  '/features': typeof FeaturesRoute
  '/how-often-does-nadac-update': typeof HowOftenDoesNadacUpdateRoute
  '/movers': typeof MoversRoute
  '/ndc-lookup': typeof NdcLookupRoute
  '/pricing': typeof PricingRoute
  '/reimbursement-calculator': typeof ReimbursementCalculatorRoute
  '/saved-calculations': typeof SavedCalculationsRoute
  '/saved-drugs': typeof SavedDrugsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/what-is-nadac': typeof WhatIsNadacRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/drug/$slug': typeof DrugSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/compare-prescription-drug-prices'
    | '/features'
    | '/how-often-does-nadac-update'
    | '/movers'
    | '/ndc-lookup'
    | '/pricing'
    | '/reimbursement-calculator'
    | '/saved-calculations'
    | '/saved-drugs'
    | '/unsubscribe'
    | '/what-is-nadac'
    | '/blog/$slug'
    | '/drug/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/compare-prescription-drug-prices'
    | '/features'
    | '/how-often-does-nadac-update'
    | '/movers'
    | '/ndc-lookup'
    | '/pricing'
    | '/reimbursement-calculator'
    | '/saved-calculations'
    | '/saved-drugs'
    | '/unsubscribe'
    | '/what-is-nadac'
    | '/blog/$slug'
    | '/drug/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/compare-prescription-drug-prices'
    | '/features'
    | '/how-often-does-nadac-update'
    | '/movers'
    | '/ndc-lookup'
    | '/pricing'
    | '/reimbursement-calculator'
    | '/saved-calculations'
    | '/saved-drugs'
    | '/unsubscribe'
    | '/what-is-nadac'
    | '/blog/$slug'
    | '/drug/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ComparePrescriptionDrugPricesRoute: typeof ComparePrescriptionDrugPricesRoute
  FeaturesRoute: typeof FeaturesRoute
  HowOftenDoesNadacUpdateRoute: typeof HowOftenDoesNadacUpdateRoute
  MoversRoute: typeof MoversRoute
  NdcLookupRoute: typeof NdcLookupRoute
  PricingRoute: typeof PricingRoute
  ReimbursementCalculatorRoute: typeof ReimbursementCalculatorRoute
  SavedCalculationsRoute: typeof SavedCalculationsRoute
  SavedDrugsRoute: typeof SavedDrugsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  WhatIsNadacRoute: typeof WhatIsNadacRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DrugSlugRoute: typeof DrugSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare-prescription-drug-prices': {
      id: '/compare-prescription-drug-prices'
      path: '/compare-prescription-drug-prices'
      fullPath: '/compare-prescription-drug-prices'
      preLoaderRoute: typeof ComparePrescriptionDrugPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-often-does-nadac-update': {
      id: '/how-often-does-nadac-update'
      path: '/how-often-does-nadac-update'
      fullPath: '/how-often-does-nadac-update'
      preLoaderRoute: typeof HowOftenDoesNadacUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movers': {
      id: '/movers'
      path: '/movers'
      fullPath: '/movers'
      preLoaderRoute: typeof MoversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ndc-lookup': {
      id: '/ndc-lookup'
      path: '/ndc-lookup'
      fullPath: '/ndc-lookup'
      preLoaderRoute: typeof NdcLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reimbursement-calculator': {
      id: '/reimbursement-calculator'
      path: '/reimbursement-calculator'
      fullPath: '/reimbursement-calculator'
      preLoaderRoute: typeof ReimbursementCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved-calculations': {
      id: '/saved-calculations'
      path: '/saved-calculations'
      fullPath: '/saved-calculations'
      preLoaderRoute: typeof SavedCalculationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved-drugs': {
      id: '/saved-drugs'
      path: '/saved-drugs'
      fullPath: '/saved-drugs'
      preLoaderRoute: typeof SavedDrugsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-is-nadac': {
      id: '/what-is-nadac'
      path: '/what-is-nadac'
      fullPath: '/what-is-nadac'
      preLoaderRoute: typeof WhatIsNadacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drug/$slug': {
      id: '/drug/$slug'
      path: '/drug/$slug'
      fullPath: '/drug/$slug'
      preLoaderRoute: typeof DrugSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ComparePrescriptionDrugPricesRoute: ComparePrescriptionDrugPricesRoute,
  FeaturesRoute: FeaturesRoute,
  HowOftenDoesNadacUpdateRoute: HowOftenDoesNadacUpdateRoute,
  MoversRoute: MoversRoute,
  NdcLookupRoute: NdcLookupRoute,
  PricingRoute: PricingRoute,
  ReimbursementCalculatorRoute: ReimbursementCalculatorRoute,
  SavedCalculationsRoute: SavedCalculationsRoute,
  SavedDrugsRoute: SavedDrugsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  WhatIsNadacRoute: WhatIsNadacRoute,
  BlogSlugRoute: BlogSlugRoute,
  DrugSlugRoute: DrugSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
